on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.12.1]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        # install dbus-1 dep for xosms
      - if: matrix.os == 'ubuntu-latest'
        name: install ubuntu deps
        run: |
          sudo apt update
          sudo apt install libdbus-1-dev snapd
          sudo snap install snapcraft --classic

      - if: matrix.os == 'windows-latest'
        name: install windows deps
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.8
        with:
          sdk-version: 19041
      - if: matrix.os == 'windows-latest'
        name: Install windows deps (node-gyp)
        shell: powershell
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}

      - name: Install dependencies
        run: |
          yarn config set ignore-engines true
          yarn

      - name: Build Electron release
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VUE_APP_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          VUE_APP_DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          VUE_APP_GITHUB_REPOSITORY: ${{ github.repository }}
